create table if not exists public.club_follows (
  id bigint generated by default as identity primary key,
  user_uid text not null,
  club_id bigint not null references public.clubs(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_uid, club_id)
);

alter table public.club_follows enable row level security;

-- The app authenticates with Firebase and stores its UID in user_uid, matching the
-- existing likes/favorites tables. Restrict the anon key at the API layer if the
-- project later adopts Supabase Auth and can bind user_uid to auth.uid().
create policy "App clients can read club follows"
on public.club_follows for select to anon, authenticated using (true);

create policy "App clients can create club follows"
on public.club_follows for insert to anon, authenticated with check (true);

create policy "App clients can remove club follows"
on public.club_follows for delete to anon, authenticated using (true);
