create table if not exists public.user_follows (
  id bigint generated by default as identity primary key,
  follower_uid text not null,
  followee_uid text not null,
  created_at timestamptz not null default now(),
  unique (follower_uid, followee_uid),
  check (follower_uid <> followee_uid)
);

alter table public.user_follows enable row level security;

-- Same trust model as club_follows: the app authenticates with Firebase and stores
-- its UID in follower_uid/followee_uid, not Supabase Auth's auth.uid(). Restrict at
-- the API layer if the project later adopts Supabase Auth.
create policy "App clients can read user follows"
on public.user_follows for select to anon, authenticated using (true);

create policy "App clients can create user follows"
on public.user_follows for insert to anon, authenticated with check (true);

create policy "App clients can remove user follows"
on public.user_follows for delete to anon, authenticated using (true);
