create table if not exists public.campus_locations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  x_pct numeric not null,
  y_pct numeric not null,
  created_at timestamptz not null default now()
);

alter table public.campus_locations enable row level security;

-- Public reference data: anyone can read. Writes are gated client-side by
-- profile.isAdmin (same posture as event_policy/club-code rotation elsewhere in
-- this app, which also has no DB-level role enforcement).
create policy "Anyone can read campus locations"
on public.campus_locations for select to anon, authenticated using (true);

create policy "App clients can manage campus locations"
on public.campus_locations for all to anon, authenticated using (true) with check (true);

insert into public.campus_locations (name, x_pct, y_pct) values
  ('Innovation Lab', 20, 25),
  ('Campus Green', 50, 50),
  ('Arts Center', 78, 22),
  ('Athletics Pavilion', 82, 75),
  ('Student Center', 48, 78),
  ('Library', 22, 70)
on conflict (name) do nothing;
