create table if not exists public.event_checkins (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  user_uid text not null,
  checked_in_at timestamptz not null default now(),
  unique (event_id, user_uid)
);

alter table public.event_checkins enable row level security;

-- Same trust model as club_follows: the app authenticates with Firebase and stores
-- its UID in user_uid, not Supabase Auth's auth.uid(). Restrict at the API layer if
-- the project later adopts Supabase Auth.
create policy "App clients can read event checkins"
on public.event_checkins for select to anon, authenticated using (true);

create policy "App clients can create event checkins"
on public.event_checkins for insert to anon, authenticated with check (true);
